#include <iostream>
#include <conio.h>
using namespace std;

bool prime (int );
int main()
{
    cout<<"PRIME NUMBERS BETWEEN 2 AND 1000 INCLUSIVE "<<endl<<endl;;
    int num=2,i,a=1000;
    bool result;
    for(i=2;i<=a;i++)
    {
        result=prime(i);
        if(result==1)
            {
                cout<<i<<" ";
            }
    }
    cout<<endl<<endl;
    getch();
}

bool prime (int num)
{
    int b;
    for(b=2;b<=num/2;b++)
        {
            if(num%b==0)
                {
                    return false;
                }
        }
    if(num%b!=0)
        {
            return true;
        }
}
